import { DataState } from "@/components/data-state";
import { api } from "@/lib/api";
import { load } from "@/lib/load";
import { label, percent } from "@/lib/format";
import { RegimeStrip } from "@/components/terminal-charts";
import { RegimeAnalytics } from "@/components/regime-analytics";

export default async function Regimes() {
  const experiments = await load(api.experiments("?limit=1")); const id = experiments.data?.items[0]?.experiment_id;
  const regimes = id ? await load(api.regimes(id)) : { data: null, error: null }; const regimeData = regimes.data;
  return <><header className="page-head"><div><p className="eyebrow">V0.2 Causal Detection</p><h1>Market Regimes</h1><p className="subtle">Rolling returns, volatility, trend slope, momentum, and drawdown observed only at or before each timestamp.</p></div></header><DataState error={experiments.error ?? regimes.error} empty={!regimeData?.items.length}>{regimeData && <><div className="metric-grid">{Object.entries(regimeData.distribution).map(([regime,count]) => <section className="metric-card" key={regime}><p>{label(regime)}</p><strong>{count}</strong><small>observations</small></section>)}</div><section className="panel"><h2>Interactive regime timeline</h2><p className="subtle">Hover bars to inspect confidence and supporting features for the persisted causal observation.</p><RegimeStrip items={regimeData.items}/></section><section className="panel"><RegimeAnalytics distribution={regimeData.distribution} observations={regimeData.items}/><p className="notice">Regime Sharpe is calculated from persisted rolling feature returns, not a separate regime-specific backtest.</p></section><div className="split"><section className="panel"><h2>Regime history</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>Regime</th><th>Confidence</th><th>Volatility</th><th>Drawdown</th></tr></thead><tbody>{regimeData.items.slice(-18).reverse().map(item => <tr key={item.timestamp}><td>{item.timestamp.slice(0,10)}</td><td>{label(item.regime)}</td><td>{percent(item.confidence)}</td><td>{percent(item.rolling_volatility)}</td><td>{percent(item.drawdown)}</td></tr>)}</tbody></table></div></section><section className="panel"><h2>Strategy performance by regime</h2>{regimeData.strategy_performance.length ? <ul className="list">{regimeData.strategy_performance.map(item => <li key={item.regime}><strong>{label(item.regime)}</strong><br/><small>{item.observations} observations · {percent(item.compounded_return)}</small></li>)}</ul> : <p className="subtle">No persisted experiment-memory performance record yet.</p>}<h3>Best / worst strategy memory</h3>{Object.entries(regimeData.best_strategies).map(([regime, entries]) => <div key={regime}><strong>{label(regime)}</strong><br/><small>Best: {entries.map(entry => `${entry.strategy} (${percent(entry.regime_return)})`).join(", ") || "—"}</small><br/><small>Worst: {regimeData.worst_strategies[regime]?.map(entry => `${entry.strategy} (${percent(entry.regime_return)})`).join(", ") || "—"}</small></div>)}</section></div></>}</DataState></>;
}
