import Link from "next/link";
import { DataState } from "@/components/data-state";
import { api } from "@/lib/api";
import { load } from "@/lib/load";
import { percent } from "@/lib/format";

export default async function CandidateDetail({ params }: { params: Promise<{ runId: string }> }) {
  const { runId } = await params; const result = await load(api.improvement(runId)); const data = result.data; const windows = data?.windows ?? [];
  return <><header className="page-head"><div><p className="eyebrow">Controlled candidate detail</p><h1>{runId}</h1><p className="subtle">Persisted V0.5 candidate evidence. It is not an automatic promotion or trading instruction.</p></div><Link className="pill" href="/improvements">Back to evolution</Link></header><DataState error={result.error} empty={!data}>{data && <><div className="metric-grid"><section className="metric-card"><p>Parent version</p><strong>{data.parent_version_id}</strong></section><section className="metric-card"><p>Decision</p><strong className={data.status === "PROMOTED" ? "good" : "bad"}>{data.status}</strong></section><section className="metric-card"><p>OOS Sharpe</p><strong>{data.candidate_metrics.sharpe_ratio?.toFixed(2) ?? "—"}</strong></section><section className="metric-card"><p>Walk-forward pass rate</p><strong>{percent(data.window_pass_rate)}</strong><small>Robustness proxy; no separate candidate robustness score was persisted.</small></section></div><div className="split"><section className="panel"><h2>Changed parameters</h2>{data.parameter_changes?.length ? <ul className="list">{data.parameter_changes.map((item, index) => <li key={index}><strong>{String(item.parameter)}</strong><br/><small>{String(item.previous_value)} → {String(item.proposed_value)}</small></li>)}</ul> : <p className="subtle">No persisted parameter change record.</p>}</section><section className="panel"><h2>Candidate metrics</h2><ul className="list"><li><strong>Return {percent(data.candidate_metrics.total_return)}</strong></li><li><strong>Drawdown {percent(data.candidate_metrics.maximum_drawdown)}</strong></li><li><strong>Transaction costs {data.candidate_metrics.total_transaction_cost?.toFixed(2) ?? "—"}</strong></li><li><strong>Reason codes</strong><br/><small>{data.reason_codes.join(", ")}</small></li></ul></section></div><section className="panel"><h2>Chronological walk-forward windows</h2><div className="table-wrap"><table><thead><tr><th>Window</th><th>Train period</th><th>Test period</th><th>Parent Sharpe</th><th>Candidate Sharpe</th><th>Candidate return</th><th>Candidate drawdown</th></tr></thead><tbody>{windows.map((item, index) => { const parent = item.parent_metrics as Record<string, number>; const candidate = item.candidate_metrics as Record<string, number>; return <tr key={index}><td>{String(item.window_index ?? index + 1)}</td><td>{String(item.train_start).slice(0,10)} – {String(item.train_end).slice(0,10)}</td><td>{String(item.test_start).slice(0,10)} – {String(item.test_end).slice(0,10)}</td><td>{parent.sharpe_ratio?.toFixed(2) ?? "—"}</td><td>{candidate.sharpe_ratio?.toFixed(2) ?? "—"}</td><td>{percent(candidate.total_return)}</td><td>{percent(candidate.maximum_drawdown)}</td></tr>; })}</tbody></table></div></section></>}</DataState></>;
}
