import { DataState } from "@/components/data-state";
import { api } from "@/lib/api";
import { load } from "@/lib/load";
import { percent } from "@/lib/format";

export default async function Improvements() {
  const [improvements, versions] = await Promise.all([load(api.improvements()), load(api.versions())]);
  return <><header className="page-head"><div><p className="eyebrow">V0.5 Controlled Evolution</p><h1>Self-Improvement</h1><p className="subtle">User-invoked, configuration-bounded candidate evaluation. No autonomous execution, code changes, or optimization beyond configured candidates.</p></div></header><DataState error={improvements.error ?? versions.error} empty={!improvements.data?.items.length && !versions.data?.items.length}>{<><div className="split"><section className="panel"><h2>Configuration lineage</h2><table><thead><tr><th>Version</th><th>Parent</th><th>Status</th><th>Candidate</th></tr></thead><tbody>{versions.data?.items.map(version => <tr key={version.version_id}><td>{version.version_id}</td><td>{version.parent_version_id ?? "—"}</td><td>{version.status}</td><td>{version.candidate_id ?? "—"}</td></tr>)}</tbody></table></section><section className="panel"><h2>Promotion guardrails</h2><ul className="list"><li><strong>Walk-forward only</strong><br/><small>Held-out periods determine candidate outcomes.</small></li><li><strong>Bounded parameters</strong><br/><small>Only configuration allowlists may change.</small></li><li><strong>Explicit invocation</strong><br/><small>Runs occur only when a user starts one.</small></li></ul></section></div><section className="panel"><h2>Candidate evaluations</h2><table><thead><tr><th>Candidate</th><th>Parent</th><th>Parameter changes</th><th>Status</th><th>OOS Sharpe</th><th>Drawdown</th><th>Pass rate</th><th>Decision</th></tr></thead><tbody>{improvements.data?.items.map(item => <tr key={item.run_id}><td>{item.run_id}</td><td>{item.parent_version_id}</td><td>{item.parameter_changes?.map(change => `${String(change.parameter)}: ${String(change.previous_value)} → ${String(change.proposed_value)}`).join("; ") || "—"}</td><td className={item.status === "PROMOTED" ? "good" : "bad"}>{item.status}</td><td>{item.candidate_metrics.sharpe_ratio?.toFixed(2) ?? "—"}</td><td>{percent(item.candidate_metrics.maximum_drawdown)}</td><td>{percent(item.window_pass_rate)}</td><td>{item.reason_codes.join(", ")}</td></tr>)}</tbody></table></section></>}</DataState></>;
}
